#!/bin/sh

# usage: ./gen_F13_as_ctrl.sh > ./AutoHotkey.d/F13_as_ctrl.ahk

echo '; generated by gen_F13_as_ctrl.sh'

for chr in $(echo 'qwrtyuiosgjklzxcvm' | grep -oE '.'); do
    echo "F13 & $chr:: send \"{Blind}{CtrlDown}$chr{CtrlUp}\""
done

# BEGIN for japanese keyboard
echo
echo '; BEGIN sign keys for japanese keyboard'
for chr in $(echo '-^\@[],./' | grep -oE '.'); do
    echo "F13 & $chr:: send \"{Blind}{CtrlDown}$chr{CtrlUp}\""
done

echo
# ; and :
echo "; ';' and :"
for chr in sc027 sc028; do
    echo "F13 & $chr:: send \"{Blind}{CtrlDown}{$chr}{CtrlUp}\""
done

echo '; END sign keys for japanese keyboard'
# END for japanese keyboard

echo

for chr in  Space Right Left Up Down; do
    echo "F13 & $chr:: send \"{Blind}{CtrlDown}{$chr}{CtrlUp}\""
done
