#!/bin/sh

# usage: ./gen_F13_as_ctrl.sh > ./AutoHotkey.d/F13_as_ctrl.ahk

echo '; generated by gen_F13_as_ctrl.sh'

for chr in $(echo 'qwtyuiosgjklzxcvm/' | grep -oE '.'); do
    echo "F13 & $chr:: send \"{Blind}{CtrlDown}$chr{CtrlUp}\""
done

echo

for chr in  Space Right Left Up Down; do
    echo "F13 & $chr:: send \"{Blind}{CtrlDown}{$chr}{CtrlUp}\""
done

# for chr in $(echo 'qwtyuiosgjklzxcvm1234567890-^\@[],./' | grep -oE '.'); do
#     echo "F13 & $chr:: send \"{Blind}{CtrlDown}$chr{CtrlUp}\""
# done

# ; and :
# for chr in sc027 sc028; do
#     echo "F13 & $chr:: send \"{Blind}{CtrlDown}{$chr}{CtrlUp}\""
# done
